name: CI/CD for springboot app

on:
  push:
    branches: [main]
jobs:
  build-and-deply:
    runs-on: ubuntu-latest
    
    steps: 
     - name : checkout source
       uses : actions/checkout@v3
     - name : setup java 17
       uses : actions/setup-java@v3
       with : 
         java-version : '17'
         distribution : 'temurin'
     - name  : build and run tests
       run  : mvn clean verify     
     - name: Deploy to Render
       if: success()  # Only if tests pass
       env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
       run: |
          curl -X POST https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json"