name: CI/CD for springboot app

on:
  push:
    branches: [main]
jobs:
  build-and-deply:
    runs-on: ubuntu-latest
    
    steps: 
     - name : checkout source
       uses : actions/checkout@v3
     - name : setup java 17
       uses : actions/setup-java@v3
       with : 
         java-version : '17'
         distribution : 'temurin'
     -name  : build and run tests
       run  : mvn clean verify     
     - name: Deploy to Render
       if: success()  # Only if tests pass
       uses: render-examples/deploy-action@v1
       with:
        serviceId: ${{ secrets.RENDER_SERVICE_ID }}
        apiKey: ${{ secrets.RENDER_API_KEY }}